# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'RspecSuite' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'fakelogin' do
    @driver.get('http://127.0.0.1:3000/login')
    #@driver.manage.resize_to(892, 706)
    @driver.find_element(:css, '.row').click
    @driver.find_element(:id, 'email').send_keys('kjgyiu;o')
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:id, 'alert').text).to eq('Email or password is invalid')
  end
  it 'fakeregistration' do
    @driver.get('http://127.0.0.1:3000/login')
    #@driver.manage.resize_to(892, 706)
    @driver.find_element(:link_text, 'Sign Up').click
    sleep 3
    #@driver.find_element(:id, 'user_email').click
    @driver.find_element(:id, 'user_email').send_keys('k k \'lm\'lm')
    @driver.find_element(:name, 'commit').click
    sleep 3
    expect(@driver.find_element(:css, 'ul:nth-child(2) > li:nth-child(1)').text).to eq('Password can\'t be blank')
  end
  it 'login' do
    @driver.get('http://127.0.0.1:3000/')
    @driver.find_element(:id, 'email').send_keys('test5@gmail.com')
    @driver.find_element(:id, 'password').send_keys('123456')
    @driver.find_element(:css, '.row').click
    @driver.find_element(:css, '.row').click
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:css, '.column:nth-child(1) .badge').text).to eq('Outgoing')
    @driver.find_element(:link_text, 'Logout').click
  end
  it 'reregistration' do
    @driver.get('http://127.0.0.1:3000/login')
    #@driver.manage.resize_to(892, 706)
    @driver.find_element(:link_text, 'Sign Up').click
    sleep  1
    @driver.find_element(:id, 'user_email').click
    @driver.find_element(:id, 'user_email').send_keys('test5@gmail.com')
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:id, 'user_password').send_keys('123456')
    @driver.find_element(:id, 'user_password_confirmation').click
    @driver.find_element(:id, 'user_password_confirmation').send_keys('123456')
    @driver.find_element(:name, 'commit').click
    sleep 1
    #@driver.find_element(:css, 'ul:nth-child(2) > li').click
    expect(@driver.find_element(:css, 'ul:nth-child(2) > li').text).to eq('Email has already been taken')
  end
  it 'sendmsg' do
    @driver.get('http://127.0.0.1:3000/login')
    #@driver.manage.resize_to(892, 706)
    # @driver.find_element(:css, '.row').click
    # @driver.find_element(:css, '.column').click
    # @driver.find_element(:css, '.row').click
    @driver.find_element(:id, 'email').send_keys('test5@gmail.com')
    @driver.find_element(:id, 'password').send_keys('123456')
    @driver.find_element(:id, 'password').send_keys(:enter)
    sleep 3
    @driver.find_element(:link_text, 'Chats').click
    sleep 2
    @driver.find_element(:css, 'tr:nth-child(1) .btn').click
    # @driver.find_element(:id, 'msgText').click
    sleep 2
    #@driver.find_element(:id, 'msgText').click
    @driver.find_element(:id, 'msgText').send_keys('hello')
    @driver.find_element(:id, 'msgText').send_keys(:enter)
    sleep 7
    expect(@driver.find_element(:css, '.msg:last-child').text).to eq('hello')
    @driver.find_element(:link_text, 'Logout').click
  end
  it 'translatelogin' do
    @driver.get('http://127.0.0.1:3000/')
    expect(@driver.find_element(:css, 'h1').text).to eq('Login')
    @driver.find_element(:link_text, 'Switch locale').click
    sleep 3
    expect(@driver.find_element(:css, 'h1').text).to eq('Войти')
    @driver.find_element(:link_text, 'Сменить язык').click
  end
  it 'translateUI' do
    @driver.get('http://127.0.0.1:3000/login')
    #@driver.manage.resize_to(892, 706)
    @driver.find_element(:id, 'email').send_keys('test5@gmail.com')
    @driver.find_element(:id, 'password').send_keys('123456')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:link_text, 'Switch locale').click
    sleep 3
    expect(@driver.find_element(:css, '.column:nth-child(1) .badge').text).to eq('Исходящие')
    @driver.find_element(:link_text, 'Сменить язык').click
    sleep 3
    @driver.find_element(:link_text, 'Logout').click
  end
  
end
